export type VillageBudget = {
  id: number;
  village_id: number;
  year: number;
  revenue: number;
  government_fund: number;
  district_fund: number;
  province_fund: number;
  local_income: number;
  community_contribution: number;
  private_sector_contribution: number;
  total_expenditure: number;
  infrastructure_realization: number;
  health_realization: number;
  education_realization: number;
  agriculture_realization: number;
  social_realization: number;
  employee_realization: number;
  employee_budget: number;
  infrastructure_budget: number;
  health_budget: number;
  education_budget: number;
  agriculture_budget: number;
  social_budget: number;
  remaining_budget: number;
  created_at: string;
  updated_at: string;
};

export type BudgetFormData = {
  year: string;
  revenue: string;
  government_fund: string;
  district_fund: string;
  province_fund: string;
  local_income: string;
  community_contribution: string;
  private_sector_contribution: string;
  employee_budget: string;
  infrastructure_budget: string;
  health_budget: string;
  education_budget: string;
  agriculture_budget: string;
  social_budget: string;
  employee_realization: string;
  infrastructure_realization: string;
  health_realization: string;
  education_realization: string;
  agriculture_realization: string;
  social_realization: string;
};
