export const TITLE_APP = "Klandesa - Dashboard Pelayanan Desa";
export const DESCRIPTION_APP =
  "Klandesa adalah sistem informasi desa digital untuk mengoptimalkan pelayanan administrasi dan masyarakat.";

// Default values for tenant village websites generated by Klandesa
export const TITLE_WEB = "Website Resmi Desa";
export const DESCRIPTION_WEB =
  "Website resmi desa yang ditenagai oleh Klandesa, platform digital desa terpercaya di Indonesia.";
export const LOGO_SINGLE_BIG = "/images/logo-single-big.png";
