// Education options (ID -> Label)
export const EDUCATION_OPTIONS: Record<string, string> = {
  "Tidak/Belum Sekolah": "Tidak/Belum Sekolah",
  "Belum Tamat SD": "Belum Tamat SD",
  "Tamat SD": "Tamat SD",
  SLTP: "SLTP",
  SLTA: "SLTA",
  "Diploma I/II": "Diploma I/II",
  "Diploma III": "Diploma III",
  "Strata I": "Strata I",
  "Strata II": "Strata II",
  "Strata III": "Strata III",
};

// Job options (ID -> Label)
export const JOB_OPTIONS: Record<string, string> = {
  "Belum/Tidak Bekerja": "Belum/Tidak Bekerja",
  "Mengurus Rumah Tangga": "Mengurus Rumah Tangga",
  "Pelajar/Mahasiswa": "Pelajar/Mahasiswa",
  Pensiunan: "Pensiunan",
  "Pegawai Negeri Sipil (PNS)": "Pegawai Negeri Sipil (PNS)",
  "Tentara Nasional Indonesia (TNI)": "Tentara Nasional Indonesia (TNI)",
  "Kepolisian RI (POLRI)": "Kepolisian RI (POLRI)",
  Perdagangan: "Perdagangan",
  "Petani/Pekebun": "Petani/Pekebun",
  Peternak: "Peternak",
  "Nelayan/Perikanan": "Nelayan/Perikanan",
  Industri: "Industri",
  Konstruksi: "Konstruksi",
  Transportasi: "Transportasi",
  "Karyawan Swasta": "Karyawan Swasta",
  "Karyawan BUMN": "Karyawan BUMN",
  "Karyawan BUMD": "Karyawan BUMD",
  "Karyawan Honorer": "Karyawan Honorer",
  "Buruh Harian Lepas": "Buruh Harian Lepas",
  "Buruh Tani/Perkebunan": "Buruh Tani/Perkebunan",
  "Buruh Nelayan/Perikanan": "Buruh Nelayan/Perikanan",
  "Buruh Peternakan": "Buruh Peternakan",
  "Pembantu Rumah Tangga": "Pembantu Rumah Tangga",
  "Tukang Cukur": "Tukang Cukur",
  "Tukang Listrik": "Tukang Listrik",
  "Tukang Batu": "Tukang Batu",
  "Tukang Kayu": "Tukang Kayu",
  "Tukang Sol Sepatu": "Tukang Sol Sepatu",
  "Tukang Las/Pandai Besi": "Tukang Las/Pandai Besi",
  "Tukang Jahit": "Tukang Jahit",
  "Tukang Gigi": "Tukang Gigi",
  "Penata Rias": "Penata Rias",
  "Penata Busana": "Penata Busana",
  "Penata Rambut": "Penata Rambut",
  Mekanik: "Mekanik",
  Seniman: "Seniman",
  Tabib: "Tabib",
  Paraji: "Paraji",
  "Perancang Busana": "Perancang Busana",
  Penterjemah: "Penterjemah",
  "Imam Masjid": "Imam Masjid",
  Pendeta: "Pendeta",
  Pastor: "Pastor",
  Wartawan: "Wartawan",
  "Ustadz/Mubaligh": "Ustadz/Mubaligh",
  "Juru Masak": "Juru Masak",
  "Promotor Acara": "Promotor Acara",
  "Anggota DPR-RI": "Anggota DPR-RI",
  "Anggota DPD": "Anggota DPD",
  "Anggota BPK": "Anggota BPK",
  Presiden: "Presiden",
  "Wakil Presiden": "Wakil Presiden",
  "Anggota Mahkamah Konstitusi": "Anggota Mahkamah Konstitusi",
  "Anggota Kabinet/Kementrian": "Anggota Kabinet/Kementrian",
  "Duta Besar": "Duta Besar",
  Gubernur: "Gubernur",
  "Wakil Gubernur": "Wakil Gubernur",
  Bupati: "Bupati",
  "Wakil Bupati": "Wakil Bupati",
  Walikota: "Walikota",
  "Wakil Walikota": "Wakil Walikota",
  "Anggota DPRD Propinsi": "Anggota DPRD Propinsi",
  "Anggota DPRD Kabupaten/Kota": "Anggota DPRD Kabupaten/Kota",
  Dosen: "Dosen",
  Guru: "Guru",
  Pilot: "Pilot",
  Pengacara: "Pengacara",
  Notaris: "Notaris",
  Arsitek: "Arsitek",
  Akuntan: "Akuntan",
  Konsultan: "Konsultan",
  Dokter: "Dokter",
  Bidan: "Bidan",
  Perawat: "Perawat",
  Apoteker: "Apoteker",
  "Psikiater/Psikolog": "Psikiater/Psikolog",
  "Penyiar Televisi": "Penyiar Televisi",
  "Penyiar Radio": "Penyiar Radio",
  Pelaut: "Pelaut",
  Peneliti: "Peneliti",
  Sopir: "Sopir",
  Pialang: "Pialang",
  Paranormal: "Paranormal",
  Pedagang: "Pedagang",
  "Perangkat Desa": "Perangkat Desa",
  "Kepala Desa": "Kepala Desa",
  Biarawati: "Biarawati",
  Wiraswasta: "Wiraswasta",
};

// Marital status options (Code -> Label)
export const MARITAL_STATUS_OPTIONS: Record<string, string> = {
  "Belum Menikah": "Belum Menikah",
  Menikah: "Menikah",
  "Cerai Hidup": "Cerai Hidup",
  "Cerai Mati": "Cerai Mati",
};

// Religion options (ID -> Label)
export const RELIGION_OPTIONS: Record<string, string> = {
  Islam: "Islam",
  Kristen: "Kristen",
  Katholik: "Katholik",
  Hindu: "Hindu",
  Budha: "Budha",
  Khonghucu: "Khonghucu",
  Kepercayaan: "Kepercayaan",
};

export const KK_RELATIONSHIP_STATUS: Record<string, string> = {
  "Kepala Keluarga": "Kepala Keluarga",
  Suami: "Suami",
  Istri: "Istri",
  Anak: "Anak",
  Menantu: "Menantu",
  Cucu: "Cucu",
  "Orang Tua": "Orang Tua",
  Mertua: "Mertua",
  "Famili Lain": "Famili Lain",
  Pembantu: "Pembantu",
  Lainnya: "Lainnya",
};

export const BLOOD_TYPE_OPTIONS: Record<string, string> = {
  A: "A",
  B: "B",
  AB: "AB",
  O: "O",
  "A+": "A+",
  "A-": "A-",
  "B+": "B+",
  "B-": "B-",
  "AB+": "AB+",
  "AB-": "AB-",
  "O+": "O+",
  "O-": "O-",
  "Tidak Tahu": "Tidak Tahu",
};

export const DISABILITY_OPTIONS: Record<string, string> = {
  "1": "1 - Cacat Fisik",
  "2": "2 - Cacat Netra/Buta",
  "3": "3 - Cacat Rungu/Wicara",
  "4": "4 - Cacat Mental/Jiwa",
  "5": "5 - Cacat Fisik dan Mental",
  "6": "6 - Cacat Lainnya",
};

export const NATIONALITY_OPTIONS: Record<string, string> = {
  WNI: "WNI",
  WNA: "WNA",
};

export const CONTRACEPTION_OPTIONS: Record<string, string> = {
  "Tidak Memakai": "Tidak Memakai",
  IUD: "IUD",
  Suntik: "Suntik",
  Pil: "Pil",
  Kondom: "Kondom",
  Implan: "Implan",
  "Steril/Pemerahan": "Steril/Pemerahan",
  Lainnya: "Lainnya",
};

export const HOUSE_OWNERSHIP_OPTIONS: Record<string, string> = {
  "Milik Sendiri": "Milik Sendiri",
  Sewa: "Sewa",
  Kontrak: "Kontrak",
  Menumpang: "Menumpang",
  Dinas: "Dinas",
  Lainnya: "Lainnya",
};

export const DESIL_OPTIONS: Record<string, string> = {
  "1": "1",
  "2": "2",
  "3": "3",
  "4": "4",
  "5": "5",
  "6": "6",
  "7": "7",
  "8": "8",
  "9": "9",
  "10": "10",
};

export const COUNTRY_CODE_OPTIONS = [
  { value: "ID", label: "Indonesia (ID)" },
  { value: "MY", label: "Malaysia (MY)" },
  { value: "SG", label: "Singapura (SG)" },
  { value: "TH", label: "Thailand (TH)" },
  { value: "PH", label: "Filipina (PH)" },
  { value: "VN", label: "Vietnam (VN)" },
  { value: "AU", label: "Australia (AU)" },
  { value: "US", label: "Amerika Serikat (US)" },
  { value: "JP", label: "Jepang (JP)" },
  { value: "KR", label: "Korea Selatan (KR)" },
  { value: "CN", label: "Tiongkok (CN)" },
  { value: "IN", label: "India (IN)" },
  { value: "GB", label: "Inggris (GB)" },
  { value: "DE", label: "Jerman (DE)" },
  { value: "FR", label: "Prancis (FR)" },
  { value: "NL", label: "Belanda (NL)" },
];
