// Education options (ID -> Label)
export const EDUCATION_OPTIONS: Record<number, string> = {
  1: "Tidak/Belum Sekolah",
  2: "Belum Tamat SD",
  3: "Tamat SD",
  4: "SLTP",
  5: "SLTA",
  6: "Diploma I/II",
  7: "Diploma III",
  8: "Strata I",
  9: "Strata II",
  10: "Strata III",
};

// Job options (ID -> Label)
export const JOB_OPTIONS: Record<number, string> = {
  1: "Belum/Tidak Bekerja",
  2: "Mengurus Rumah Tangga",
  3: "Pelajar/Mahasiswa",
  4: "Pensiunan",
  5: "Pegawai Negeri Sipil (PNS)",
  6: "Tentara Nasional Indonesia (TNI)",
  7: "Kepolisian RI (POLRI)",
  8: "Perdagangan",
  9: "Petani/Pekebun",
  10: "Peternak",
  11: "Nelayan/Perikanan",
  12: "Industri",
  13: "Konstruksi",
  14: "Transportasi",
  15: "Karyawan Swasta",
  16: "Karyawan BUMN",
  17: "Karyawan BUMD",
  18: "Karyawan Honorer",
  19: "Buruh Harian Lepas",
  20: "Buruh Tani/Perkebunan",
  21: "Buruh Nelayan/Perikanan",
  22: "Buruh Peternakan",
  23: "Pembantu Rumah Tangga",
  24: "Tukang Cukur",
  25: "Tukang Listrik",
  26: "Tukang Batu",
  27: "Tukang Kayu",
  28: "Tukang Sol Sepatu",
  29: "Tukang Las/Pandai Besi",
  30: "Tukang Jahit",
  31: "Tukang Gigi",
  32: "Penata Rias",
  33: "Penata Busana",
  34: "Penata Rambut",
  35: "Mekanik",
  36: "Seniman",
  37: "Tabib",
  38: "Paraji",
  39: "Perancang Busana",
  40: "Penterjemah",
  41: "Imam Masjid",
  42: "Pendeta",
  43: "Pastor",
  44: "Wartawan",
  45: "Ustadz/Mubaligh",
  46: "Juru Masak",
  47: "Promotor Acara",
  48: "Anggota DPR-RI",
  49: "Anggota DPD",
  50: "Anggota BPK",
  51: "Presiden",
  52: "Wakil Presiden",
  53: "Anggota Mahkamah Konstitusi",
  54: "Anggota Kabinet/Kementrian",
  55: "Duta Besar",
  56: "Gubernur",
  57: "Wakil Gubernur",
  58: "Bupati",
  59: "Wakil Bupati",
  60: "Walikota",
  61: "Wakil Walikota",
  62: "Anggota DPRD Propinsi",
  63: "Anggota DPRD Kabupaten/Kota",
  64: "Dosen",
  65: "Guru",
  66: "Pilot",
  67: "Pengacara",
  68: "Notaris",
  69: "Arsitek",
  70: "Akuntan",
  71: "Konsultan",
  72: "Dokter",
  73: "Bidan",
  74: "Perawat",
  75: "Apoteker",
  76: "Psikiater/Psikolog",
  77: "Penyiar Televisi",
  78: "Penyiar Radio",
  79: "Pelaut",
  80: "Peneliti",
  81: "Sopir",
  82: "Pialang",
  83: "Paranormal",
  84: "Pedagang",
  85: "Perangkat Desa",
  86: "Kepala Desa",
  87: "Biarawati",
  88: "Wiraswasta",
};

// Marital status options (Code -> Label)
export const MARITAL_STATUS_OPTIONS: Record<string, string> = {
  S: "Belum Menikah",
  M: "Menikah",
  D: "Cerai Hidup",
  DD: "Cerai Mati",
};

// Religion options (ID -> Label)
export const RELIGION_OPTIONS: Record<number, string> = {
  1: "Islam",
  2: "Kristen",
  3: "Katholik",
  4: "Hindu",
  5: "Budha",
  6: "Khonghucu",
  7: "Kepercayaan",
};

export const KK_RELATIONSHIP_STATUS: Record<number, string> = {
  1: "Kepala Keluarga",
  2: "Suami",
  3: "Istri",
  4: "Anak",
  5: "Menantu",
  6: "Cucu",
  7: "Orang Tua",
  8: "Mertua",
  9: "Famili Lain",
  10: "Pembantu",
  11: "Lainnya",
};

export const BLOOD_TYPE_OPTIONS: Record<number, string> = {
  1: "A",
  2: "B",
  3: "AB",
  4: "O",
  5: "A+",
  6: "A-",
  7: "B+",
  8: "B-",
  9: "AB+",
  10: "AB-",
  11: "O+",
  12: "O-",
  13: "Tidak Tahu",
};

export const DISABILITY_OPTIONS: Record<number, string> = {
  1: "Cacat Fisik",
  2: "Cacat Netra/Buta",
  3: "Cacat Rungu/Wicara",
  4: "Cacat Mental/Jiwa",
  5: "Cacat Fisik dan Mental",
  6: "Cacat Lainnya",
};
