import type { PermissionResource } from "@/lib/permissions";

export type ModuleStatus = "live" | "beta" | "planned";

export type ModuleDefinition = {
  id: string;
  label: string;
  path?: string;
  permission: PermissionResource;
  sdgGoals: number[];
  status: ModuleStatus;
  /** ID menu parent untuk grouping sidebar */
  group?: string;
  groupLabel?: string;
  sortOrder: number;
  billingAddon?: string;
};

/** Registry modul desa — live + planned. Sidebar & landing baca dari sini. */
export const VILLAGE_MODULE_REGISTRY: ModuleDefinition[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    permission: "statistics",
    sdgGoals: [17],
    status: "live",
    sortOrder: 10,
  },
  {
    id: "data-warga",
    label: "Warga",
    path: "/data-warga",
    permission: "residents",
    sdgGoals: [1, 4, 10, 18],
    status: "live",
    group: "data",
    groupLabel: "Data",
    sortOrder: 20,
  },
  {
    id: "data-kk",
    label: "Kartu Keluarga",
    path: "/data-kk",
    permission: "residents",
    sdgGoals: [1, 10],
    status: "live",
    group: "data",
    sortOrder: 30,
  },
  {
    id: "data-perangkat",
    label: "Perangkat Desa",
    path: "/data-perangkat",
    permission: "officials",
    sdgGoals: [16, 18],
    status: "live",
    group: "data",
    sortOrder: 40,
  },
  {
    id: "data-jabatan",
    label: "Jabatan",
    path: "/data-jabatan",
    permission: "officials",
    sdgGoals: [18],
    status: "live",
    group: "data",
    sortOrder: 50,
  },
  {
    id: "potensi",
    label: "Potensi",
    path: "/potensi",
    permission: "potentials",
    sdgGoals: [2, 8, 15],
    status: "live",
    group: "data",
    sortOrder: 60,
  },
  {
    id: "anggaran",
    label: "Anggaran",
    path: "/anggaran",
    permission: "anggaran",
    sdgGoals: [16, 17],
    status: "live",
    group: "data",
    sortOrder: 70,
  },
  {
    id: "koperasi",
    label: "Koperasi",
    path: "/koperasi",
    permission: "cooperative",
    sdgGoals: [8],
    status: "live",
    group: "data",
    sortOrder: 75,
  },
  {
    id: "bumdes",
    label: "BUMDes",
    path: "/bumdes",
    permission: "bumdes",
    sdgGoals: [2, 8],
    status: "beta",
    group: "data",
    sortOrder: 76,
    billingAddon: "bumdes",
  },
  {
    id: "statistik",
    label: "Statistik",
    path: "/statistik",
    permission: "statistics",
    sdgGoals: [1, 4, 10],
    status: "live",
    sortOrder: 80,
  },
  {
    id: "permohonan-warga",
    label: "Permohonan Warga",
    path: "/permohonan-warga",
    permission: "mail",
    sdgGoals: [16],
    status: "live",
    group: "pelayanan",
    groupLabel: "Pelayanan Surat",
    sortOrder: 90,
  },
  {
    id: "layanan-mandiri",
    label: "Layanan Mandiri",
    path: "/layanan-mandiri",
    permission: "mail",
    sdgGoals: [16],
    status: "live",
    group: "pelayanan",
    sortOrder: 100,
  },
  {
    id: "layanan-surat",
    label: "Layanan Surat",
    path: "/layanan-surat",
    permission: "mail",
    sdgGoals: [16],
    status: "live",
    group: "pelayanan",
    sortOrder: 110,
  },
  {
    id: "pengaturan-desa",
    label: "Pengaturan Desa",
    path: "/pengaturan-desa",
    permission: "settings",
    sdgGoals: [18],
    status: "live",
    group: "pelayanan",
    sortOrder: 120,
  },
  {
    id: "keuangan",
    label: "Sistem Keuangan",
    path: "/keuangan",
    permission: "finance",
    sdgGoals: [16, 17],
    status: "live",
    sortOrder: 130,
  },
  {
    id: "billing",
    label: "Billing",
    path: "/billing",
    permission: "billing",
    sdgGoals: [],
    status: "live",
    sortOrder: 140,
  },
  {
    id: "pengumuman-desa",
    label: "Pengumuman",
    path: "/pengumuman-desa",
    permission: "announcements",
    sdgGoals: [16],
    status: "live",
    group: "portal",
    groupLabel: "Portal Warga",
    sortOrder: 150,
  },
  {
    id: "forum-diskusi",
    label: "Forum Diskusi",
    path: "/forum-diskusi",
    permission: "forum",
    sdgGoals: [16],
    status: "live",
    group: "portal",
    sortOrder: 160,
  },
  {
    id: "pengaduan-masyarakat",
    label: "Aduan Warga",
    path: "/pengaduan-masyarakat",
    permission: "citizen_reports",
    sdgGoals: [16],
    status: "live",
    group: "portal",
    sortOrder: 170,
  },
  {
    id: "bantuan-program-keluarga",
    label: "Bansos & PKH",
    path: "/bantuan-program-keluarga",
    permission: "social_benefits",
    sdgGoals: [1, 10],
    status: "live",
    group: "portal",
    sortOrder: 180,
  },
  {
    id: "galeri-desa",
    label: "Galeri Desa",
    path: "/galeri-desa",
    permission: "announcements",
    sdgGoals: [16],
    status: "live",
    group: "portal",
    sortOrder: 190,
  },
  {
    id: "absensi",
    label: "Absensi Perangkat",
    path: "/absensi",
    permission: "attendance",
    sdgGoals: [16],
    status: "live",
    sortOrder: 200,
  },
  {
    id: "pkk",
    label: "PKK & Dasawisma",
    path: "/pkk",
    permission: "pkk",
    sdgGoals: [3, 5],
    status: "beta",
    sortOrder: 205,
    billingAddon: "pkk",
  },
  {
    id: "sdgs",
    label: "Dashboard SDGs",
    path: "/sdgs",
    permission: "sdgs",
    sdgGoals: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
    status: "beta",
    sortOrder: 210,
    billingAddon: "sdgs",
  },
  {
    id: "rpjmdes",
    label: "RPJMDes",
    path: "/rpjmdes",
    permission: "rpjmdes",
    sdgGoals: [17, 18],
    status: "beta",
    sortOrder: 215,
    billingAddon: "sdgs",
  },
  {
    id: "pertanian",
    label: "Pertanian",
    path: "/pertanian",
    permission: "pertanian",
    sdgGoals: [2, 8, 15],
    status: "beta",
    sortOrder: 220,
  },
  {
    id: "partisipasi-rtrw",
    label: "Partisipasi RT/RW",
    path: "/partisipasi-rtrw",
    permission: "rtrw",
    sdgGoals: [16, 17, 18],
    status: "beta",
    sortOrder: 225,
  },
  {
    id: "sinkronisasi-data",
    label: "Sinkronisasi Data",
    path: "/sinkronisasi-data",
    permission: "integrations",
    sdgGoals: [17],
    status: "beta",
    sortOrder: 230,
    billingAddon: "integrations",
  },
  {
    id: "peta-infrastruktur",
    label: "Peta Infrastruktur",
    path: "/peta-infrastruktur",
    permission: "gis",
    sdgGoals: [9, 11, 13],
    status: "beta",
    sortOrder: 235,
    billingAddon: "gis",
  },
  {
    id: "lingkungan",
    label: "Lingkungan",
    path: "/lingkungan",
    permission: "lingkungan",
    sdgGoals: [6, 11, 12, 13, 15],
    status: "beta",
    sortOrder: 240,
  },
  {
    id: "asisten-ai",
    label: "Asisten AI",
    path: "/asisten-ai",
    permission: "ai_assistant",
    sdgGoals: [17],
    status: "beta",
    sortOrder: 245,
    billingAddon: "ai_assistant",
  },
  {
    id: "arsip",
    label: "Arsip Digital",
    path: "/arsip",
    permission: "archive",
    sdgGoals: [16],
    status: "live",
    sortOrder: 250,
  },
  {
    id: "ukm",
    label: "Produk UKM",
    path: "/ukm",
    permission: "ukm",
    sdgGoals: [8],
    status: "live",
    sortOrder: 255,
  },
  {
    id: "website",
    label: "Website Desa",
    path: "/website",
    permission: "website",
    sdgGoals: [17],
    status: "live",
    sortOrder: 270,
  },
];

export function getNavModules(): ModuleDefinition[] {
  return VILLAGE_MODULE_REGISTRY.filter(
    (m) => m.status === "live" || m.status === "beta",
  );
}

/** @deprecated Gunakan getNavModules */
export function getLiveModules(): ModuleDefinition[] {
  return getNavModules();
}

export function getModuleById(id: string): ModuleDefinition | undefined {
  return VILLAGE_MODULE_REGISTRY.find((m) => m.id === id);
}
